// Default categories
export const DEFAULT_CATEGORIES = {
  ar: [
    { id: "1", name: "الكهربائيات" },
    { id: "2", name: "الأثاث" },
    { id: "3", name: "المطبخ" },
    { id: "4", name: "الحمام" },
    { id: "5", name: "غرفة النوم" },
  ],
  en: [
    { id: "1", name: "Electronics" },
    { id: "2", name: "Furniture" },
    { id: "3", name: "Kitchen" },
    { id: "4", name: "Bathroom" },
    { id: "5", name: "Bedroom" },
  ],
}

// Default items for each budget mode
export const DEFAULT_ITEMS = {
  economic: {
    ar: [
      // Electronics - الكهربائيات
      {
        id: "e1",
        categoryId: "1",
        name: "ثلاجة",
        price: 5000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "e2",
        categoryId: "1",
        name: "غسالة",
        price: 3000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "e3",
        categoryId: "1",
        name: "تلفزيون",
        price: 2500000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Furniture - الأثاث
      {
        id: "e4",
        categoryId: "2",
        name: "طقم كنب",
        price: 5000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "e5",
        categoryId: "2",
        name: "طاولة طعام",
        price: 2000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "e6",
        categoryId: "2",
        name: "خزانة ملابس",
        price: 3000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Kitchen - المطبخ
      {
        id: "e7",
        categoryId: "3",
        name: "أدوات مطبخ",
        price: 1500000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "e8",
        categoryId: "3",
        name: "فرن",
        price: 2000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Bathroom - الحمام
      {
        id: "e9",
        categoryId: "4",
        name: "أدوات حمام",
        price: 1000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Bedroom - غرفة النوم
      {
        id: "e10",
        categoryId: "5",
        name: "سرير",
        price: 3000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "e11",
        categoryId: "5",
        name: "مراتب",
        price: 2000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
    ],
    en: [
      // Electronics
      {
        id: "e1",
        categoryId: "1",
        name: "Refrigerator",
        price: 5000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "e2",
        categoryId: "1",
        name: "Washing Machine",
        price: 3000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "e3",
        categoryId: "1",
        name: "Television",
        price: 2500000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Furniture
      {
        id: "e4",
        categoryId: "2",
        name: "Sofa Set",
        price: 5000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "e5",
        categoryId: "2",
        name: "Dining Table",
        price: 2000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "e6",
        categoryId: "2",
        name: "Wardrobe",
        price: 3000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Kitchen
      {
        id: "e7",
        categoryId: "3",
        name: "Kitchen Utensils",
        price: 1500000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "e8",
        categoryId: "3",
        name: "Oven",
        price: 2000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Bathroom
      {
        id: "e9",
        categoryId: "4",
        name: "Bathroom Accessories",
        price: 1000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Bedroom
      {
        id: "e10",
        categoryId: "5",
        name: "Bed",
        price: 3000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "e11",
        categoryId: "5",
        name: "Mattress",
        price: 2000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
    ],
  },
  medium: {
    ar: [
      // Electronics - الكهربائيات
      {
        id: "m1",
        categoryId: "1",
        name: "ثلاجة متوسطة",
        price: 8000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "m2",
        categoryId: "1",
        name: "غسالة أوتوماتيك",
        price: 6000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "m3",
        categoryId: "1",
        name: "تلفزيون سمارت",
        price: 5000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Furniture - الأثاث
      {
        id: "m4",
        categoryId: "2",
        name: "طقم كنب جلد",
        price: 10000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "m5",
        categoryId: "2",
        name: "طاولة طعام خشب",
        price: 4000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "m6",
        categoryId: "2",
        name: "خزانة ملابس كبيرة",
        price: 6000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Kitchen - المطبخ
      {
        id: "m7",
        categoryId: "3",
        name: "أدوات مطبخ كاملة",
        price: 3000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "m8",
        categoryId: "3",
        name: "فرن كهربائي",
        price: 4000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Bathroom - الحمام
      {
        id: "m9",
        categoryId: "4",
        name: "أدوات حمام متكاملة",
        price: 2500000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Bedroom - غرفة النوم
      {
        id: "m10",
        categoryId: "5",
        name: "سرير مزدوج",
        price: 6000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "m11",
        categoryId: "5",
        name: "مراتب طبية",
        price: 4000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
    ],
    en: [
      // Electronics
      {
        id: "m1",
        categoryId: "1",
        name: "Mid-range Refrigerator",
        price: 8000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "m2",
        categoryId: "1",
        name: "Automatic Washing Machine",
        price: 6000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "m3",
        categoryId: "1",
        name: "Smart TV",
        price: 5000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Furniture
      {
        id: "m4",
        categoryId: "2",
        name: "Leather Sofa Set",
        price: 10000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "m5",
        categoryId: "2",
        name: "Wooden Dining Table",
        price: 4000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "m6",
        categoryId: "2",
        name: "Large Wardrobe",
        price: 6000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Kitchen
      {
        id: "m7",
        categoryId: "3",
        name: "Complete Kitchen Set",
        price: 3000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "m8",
        categoryId: "3",
        name: "Electric Oven",
        price: 4000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Bathroom
      {
        id: "m9",
        categoryId: "4",
        name: "Complete Bathroom Set",
        price: 2500000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Bedroom
      {
        id: "m10",
        categoryId: "5",
        name: "Double Bed",
        price: 6000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "m11",
        categoryId: "5",
        name: "Orthopedic Mattress",
        price: 4000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
    ],
  },
  luxury: {
    ar: [
      // Electronics - الكهربائيات
      {
        id: "l1",
        categoryId: "1",
        name: "ثلاجة فاخرة",
        price: 15000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "l2",
        categoryId: "1",
        name: "غسالة وتنشيف",
        price: 12000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "l3",
        categoryId: "1",
        name: "تلفزيون OLED",
        price: 10000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Furniture - الأثاث
      {
        id: "l4",
        categoryId: "2",
        name: "طقم كنب فاخر",
        price: 20000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "l5",
        categoryId: "2",
        name: "طاولة طعام فاخرة",
        price: 8000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "l6",
        categoryId: "2",
        name: "خزانة ملابس مخصصة",
        price: 12000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Kitchen - المطبخ
      {
        id: "l7",
        categoryId: "3",
        name: "أدوات مطبخ فاخرة",
        price: 6000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "l8",
        categoryId: "3",
        name: "فرن مدمج",
        price: 8000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Bathroom - الحمام
      {
        id: "l9",
        categoryId: "4",
        name: "أدوات حمام فاخرة",
        price: 5000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Bedroom - غرفة النوم
      {
        id: "l10",
        categoryId: "5",
        name: "سرير كينغ",
        price: 12000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "l11",
        categoryId: "5",
        name: "مراتب فاخرة",
        price: 8000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
    ],
    en: [
      // Electronics
      {
        id: "l1",
        categoryId: "1",
        name: "Luxury Refrigerator",
        price: 15000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "l2",
        categoryId: "1",
        name: "Washer & Dryer",
        price: 12000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "l3",
        categoryId: "1",
        name: "OLED TV",
        price: 10000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Furniture
      {
        id: "l4",
        categoryId: "2",
        name: "Premium Sofa Set",
        price: 20000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "l5",
        categoryId: "2",
        name: "Luxury Dining Table",
        price: 8000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "l6",
        categoryId: "2",
        name: "Custom Wardrobe",
        price: 12000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Kitchen
      {
        id: "l7",
        categoryId: "3",
        name: "Premium Kitchen Utensils",
        price: 6000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "l8",
        categoryId: "3",
        name: "Built-in Oven",
        price: 8000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Bathroom
      {
        id: "l9",
        categoryId: "4",
        name: "Luxury Bathroom Accessories",
        price: 5000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      // Bedroom
      {
        id: "l10",
        categoryId: "5",
        name: "King Size Bed",
        price: 12000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
      {
        id: "l11",
        categoryId: "5",
        name: "Premium Mattress",
        price: 8000000,
        isInstallment: false,
        monthlyInstallment: 0,
        installmentMonths: 0,
        currency: "SYP",
      },
    ],
  },
}